implemented event deletion
gdsc-conestoga/website pull request #32
Opened 2022-03-22 03:54 UTC by larrycoal

## Description

This PR implement event deletion 

## Issue

This PR fixes #27 

##Blocker
Has permission issue that probably needs to be fixed on firebase dev console

2022-03-30 23:13 UTC, ANDREYDEN requested changes
Looks great! I believe the issue with insufficient permissions is due to some work that I have done on the Auth branch #31. I'll merge that in ASAP and get back to you when that is ready.

2022-03-30 23:13 UTC, ANDREYDEN commented on package.json
> +    "@mui/material": "^5.5.2",
I believe only `@mui/icons-material` is used in this PR, are other packages needed?

2022-04-04 21:09 UTC, ANDREYDEN commented
@larrycoal, sorry this took so long, but I finally merged the authentication (#31) branch. You should be able to test your functionality with Firebase Emulators (`npm run emulate`). Your branch now also has some conflicts, so you might want to merge `main` into your branch.

2022-04-04 23:40 UTC, ANDREYDEN commented on package.json
> +    "@mui/material": "^5.5.2",
nvm, now I see they are needed

2022-04-11 01:33 UTC, ANDREYDEN requested changes
Something weird happened when you merged `master` into your branch resulting in 34 file differences. While it seems like most of the changes are just duplicates from previous commits, there are some places you might need to be careful with. Those are mostly the documents you edited to achieve the 'delete' functionality

2022-04-11 01:33 UTC, ANDREYDEN commented on src/pages/calendar/Calendar.jsx
> +import InputField from "../../components/inputField/InputField";
These imports throw errors when you run the app

2022-04-11 01:33 UTC, ANDREYDEN commented on src/pages/calendar/Calendar.jsx
> +      <CustomButton onClick={openEventModal} type="button" buttonText="+" />
This button should only be shown when the user is an admin (current behavior on `master`)

2022-04-11 01:33 UTC, ANDREYDEN commented on src/pages/calendar/Calendar.jsx
> +        <Delete
This button should only be shown for admins.

2022-04-16 20:06 UTC, larrycoal commented on src/pages/calendar/Calendar.jsx
> +import InputField from "../../components/inputField/InputField";
While trying to resolve conflict, i messed up my commit history

2022-04-17 16:30 UTC, ANDREYDEN commented on src/pages/calendar/Calendar.jsx
> +import InputField from "../../components/inputField/InputField";
@larrycoal, do you mind recreating the PR with only your changes or trying to merge `master` in again?

2022-04-17 16:31 UTC, larrycoal commented on src/pages/calendar/Calendar.jsx
> +import InputField from "../../components/inputField/InputField";
will start from scratch and open new PR

2022-05-03 02:59 UTC, closed without merging